### ISSUE TITLE
CompExample misses model files

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#15]
Test model for CompExample missing from repository.
```
Exception in thread "main" java.io.FileNotFoundException: files/comp/test58.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBML(SBMLReader.java:295)
	at org.sbml.jsbml.SBMLReader.readSBML(SBMLReader.java:116)
	at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:105)
	at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:92)
	at org.simulator.CompExample.main(CompExample.java:92)
```
Please add the test/example files to the repo.

**Comment by draeger** [comment]
Should we really do this? It will add a large number of redundant files. Wouldn't it be a better approach to use an environment variable that specifies the location of the files?

**Comment by shalinshah1993** [comment]
I agree with @draeger when I am finished with this feature instead of taking the hard-coded path as input, I can just use command line args otherwise it will add a lot of files. However, we can add one example if you like. 


You can download example files from this jsbml commit https://github.com/sbmlteam/jsbml/commit/46ca561edbca85a1f05f14dcc6e08acd65b2e235

**Comment by matthiaskoenig** [comment]
I would add a minimal set of test models in the repository which allows to run the core set of unit tests on the project. These tests would be very specific. There should be a way to test the core functionality without the need to run 10000 tests (i.e. all testsuite cases).

In addition there would be a large set of generic test, i.e. running test suite, running BiGG models.
