### ISSUE TITLE
ConstraintTest misses model file

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#16]
ConstraintTest misses the model file `data/Constraint-00001-L3V1.xml`
```
Exception in thread "main" java.lang.IllegalArgumentException: Null InputStream is not a valid argument
	at com.ctc.wstx.stax.WstxInputFactory.createSR(WstxInputFactory.java:643)
	at com.ctc.wstx.stax.WstxInputFactory.createXMLEventReader(WstxInputFactory.java:272)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:541)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:552)
	at org.sbml.jsbml.SBMLReader.readSBMLFromStream(SBMLReader.java:251)
	at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:128)
	at org.simulator.sbml.ConstraintTest.main(ConstraintTest.java:64)
```

**Comment by shalinshah1993** [comment]
The required files for constraint-based models are inside `files` folder. There is a biomodels zip folder. In my case, it is: `SBSCL\files\Biomodels_release_20110415\release_20110415\curated\`

**Comment by draeger** [comment]
Just a note: within Java one should always use `/` as a path delimiter rather than `\`. Java automatically converts this as needed.

**Comment by shalinshah1993** [comment]
Commit for the fix can be found [here](https://github.com/shalinshah1993/SBSCL/commit/1d840c656810ad6a61ac675626b5214b2dd8cb35). Closing this issue!
